import pyvista as pv
import pandas as pd
import numpy as np
import struct
import sys
import os
import json
import time
from collections import defaultdict

# Единственная папка workspace лежит рядом с этим скриптом (в корне проекта).
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Загрузка пользовательских настроек визуализатора (цвета, камера, прозрачность).
VIZ_CONFIG_PATH = os.path.join(SCRIPT_DIR, "workspace", "configs", "visualizer.json")


def _load_viz_config():
    if not os.path.exists(VIZ_CONFIG_PATH):
        return {}
    try:
        with open(VIZ_CONFIG_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"  (warning: cannot read {VIZ_CONFIG_PATH}: {e})")
        return {}

VIZ_CFG = _load_viz_config()


def load_trajectories(bin_path):
    """Reads binary trajectory data generated by the C++ engine."""
    particles = []
    if not os.path.exists(bin_path):
        print(f"!!! Trajectory file not found: {bin_path}")
        return particles
    try:
        with open(bin_path, "rb") as f:
            while True:
                header = f.read(4)
                if not header:
                    break
                n_points = struct.unpack("I", header)[0]
                points = np.fromfile(f, dtype=np.float64, count=n_points * 3).reshape(-1, 3)
                particles.append(points)
    except Exception as e:
        print(f"Error reading binary file: {e}")
    return particles


def build_combined_mesh(base, transforms_np):
    """
    Склеить N трансформированных копий `base` в один PolyData.

    Порядок поворотов соответствует исходному pyvista-коду:
      mesh.rotate_z(yaw) -> rotate_y(pitch) -> rotate_x(roll)
    то есть полный поворот R = R_x(roll) @ R_y(pitch) @ R_z(yaw).

    transforms_np: ndarray (n_inst, 6) -- столбцы (yaw, pitch, roll, tx, ty, tz),
                   углы в радианах.

    Реализация полностью векторизована через numpy + einsum -- ни одного
    Python-цикла по экземплярам или VTK-вызова на копию.
    """
    pts_base = np.asarray(base.points, dtype=np.float64)
    n_pts = pts_base.shape[0]
    n_inst = transforms_np.shape[0]

    yaws    = transforms_np[:, 0]
    pitches = transforms_np[:, 1]
    rolls   = transforms_np[:, 2]
    trans   = transforms_np[:, 3:6]  # (n_inst, 3)

    sy, cy = np.sin(yaws),    np.cos(yaws)
    sp, cp = np.sin(pitches), np.cos(pitches)
    sr, cr = np.sin(rolls),   np.cos(rolls)

    R = np.empty((n_inst, 3, 3))
    R[:, 0, 0] = cp * cy
    R[:, 0, 1] = -cp * sy
    R[:, 0, 2] = sp
    R[:, 1, 0] = sr * sp * cy + cr * sy
    R[:, 1, 1] = -sr * sp * sy + cr * cy
    R[:, 1, 2] = -sr * cp
    R[:, 2, 0] = -cr * sp * cy + sr * sy
    R[:, 2, 1] = cr * sp * sy + sr * cy
    R[:, 2, 2] = cr * cp

    # all_pts[i, k, :] = R[i] @ pts_base[k] + trans[i]
    all_pts = np.einsum("nij,kj->nki", R, pts_base) + trans[:, None, :]
    flat_pts = all_pts.reshape(-1, 3)

    # STL всегда триангулирован: face = [3, v0, v1, v2].
    faces_base = np.asarray(base.faces, dtype=np.int64)
    if faces_base.size == 0 or faces_base[0] != 3:
        return pv.PolyData(flat_pts[:n_pts])
    faces_reshaped = faces_base.reshape(-1, 4)
    n_tri = faces_reshaped.shape[0]
    all_faces = np.broadcast_to(faces_reshaped, (n_inst, n_tri, 4)).copy()
    offsets = (np.arange(n_inst) * n_pts)[:, None, None]
    all_faces[:, :, 1:] += offsets
    flat_faces = all_faces.reshape(-1)

    return pv.PolyData(flat_pts, flat_faces)


def visualize(target_exp_id):
    t_start = time.time()
    ws = os.path.join(SCRIPT_DIR, "workspace") + os.sep
    print(f"\n{'=' * 50}\nVISUALIZING EXPERIMENT ID: {target_exp_id}\n{'=' * 50}")

    plotter = pv.Plotter(title=f"Synchrotron Tracker - Exp {target_exp_id}")
    plotter.set_background(VIZ_CFG.get("background", "white"))

    # 1. CSV -----------------------------------------------------------------
    t0 = time.time()
    try:
        exp_df     = pd.read_csv(ws + "tables/experiments.csv",      sep=";", skipinitialspace=True)
        lattice_df = pd.read_csv(ws + "tables/lattice_configs.csv",  sep=";", skipinitialspace=True)
        hw_df      = pd.read_csv(ws + "tables/hardware_library.csv", sep=";", skipinitialspace=True)
    except Exception as e:
        print(f"Error loading CSVs: {e}")
        return

    exp_row = exp_df[exp_df["exp_id"] == target_exp_id]
    if exp_row.empty:
        print(f"Error: Experiment ID {target_exp_id} not found.")
        return
    lat_id = int(exp_row["lattice_id"].iloc[0])
    current_lat = lattice_df[lattice_df["lattice_id"] == lat_id]
    print(f"  CSVs loaded in {time.time() - t0:.2f}s | lattice {lat_id}: {len(current_lat)} instances")

    # 2. hardware_library в словарь --------------------------------------------
    hw_lookup = {}
    for row in hw_df.itertuples():
        dev_id = str(getattr(row, "device_type_id", "")).strip()
        if not dev_id or dev_id == "nan":
            continue
        stl_name  = str(getattr(row, "stl_path", "")).strip()
        is_active = str(getattr(row, "Active", "")).strip().lower() in ("true", "1", "yes")
        hw_lookup[dev_id] = (stl_name, is_active)

    # 3. STL читаем один раз на уникальный файл -------------------------------
    t0 = time.time()
    stl_cache = {}
    for stl_name, _ in hw_lookup.values():
        if stl_name in ("-", "", "nan") or stl_name in stl_cache:
            continue
        path = os.path.join(ws, "geometry", stl_name)
        if os.path.exists(path):
            m = pv.read(path)
            m.scale(0.001, inplace=True)  # мм -> м, один раз
            stl_cache[stl_name] = m
        else:
            stl_cache[stl_name] = None
    n_unique_stl = sum(1 for v in stl_cache.values() if v is not None)
    print(f"  Cached {n_unique_stl} unique STL meshes in {time.time() - t0:.2f}s")

    # 4. Группировка по типу устройства ---------------------------------------
    t0 = time.time()
    dev_ids = current_lat["device_type_id"].astype(str).str.strip().values
    yaws    = current_lat["yaw"].astype(float).values
    pitches = current_lat["pitch"].astype(float).values
    rolls   = current_lat["roll"].astype(float).values
    xs      = current_lat["x"].astype(float).values
    ys      = current_lat["y"].astype(float).values
    zs      = current_lat["z"].astype(float).values

    grouped = defaultdict(list)
    unknown_type, no_stl = 0, 0
    for i in range(len(dev_ids)):
        dev = dev_ids[i]
        if dev not in hw_lookup:
            unknown_type += 1
            continue
        stl_name, _ = hw_lookup[dev]
        if stl_cache.get(stl_name) is None:
            no_stl += 1
            continue
        grouped[dev].append((yaws[i], pitches[i], rolls[i], xs[i], ys[i], zs[i]))
    print(f"  Grouped into {len(grouped)} device types in {time.time() - t0:.2f}s")
    if no_stl:
        print(f"  ({no_stl} instances skipped - device has no STL)")
    if unknown_type:
        print(f"  ({unknown_type} instances skipped - unknown type)")

    # 5. Один меш на тип устройства, один add_mesh на тип ---------------------
    t0 = time.time()
    total_polys = 0
    for dev, tlist in grouped.items():
        base = stl_cache[hw_lookup[dev][0]]
        tr_np = np.asarray(tlist, dtype=np.float64)
        big = build_combined_mesh(base, tr_np)
        is_active = hw_lookup[dev][1]
        op = VIZ_CFG.get("lattice_opacity", {})
        opacity = float(op.get("EM", 0.25) if is_active else op.get("PM", 0.4))
        plotter.add_mesh(
            big, color="silver", opacity=opacity, show_edges=True,
            label=f"{dev} ({'EM' if is_active else 'PM'}, x{len(tlist)})",
        )
        total_polys += big.n_cells
    print(f"  Built and added {len(grouped)} merged meshes "
          f"({total_polys:,} polygons total) in {time.time() - t0:.2f}s")

    # 6. Траектории ------------------------------------------------------------
    t0 = time.time()
    bin_path = os.path.join(ws, "results", f"trajectories_exp{target_exp_id}.bin")
    print(f"  Trajectory source: {bin_path}")
    particles = load_trajectories(bin_path)
    if particles:
        colors = VIZ_CFG.get("particle_colors",
                             ["magenta", "cyan", "lime", "yellow", "red"])
        labels = VIZ_CFG.get("particle_labels",
                             ["P1 (ref)", "P2 (+Y)", "P3 (-Y)", "P4 (+Z)", "P5 (-Z)"])
        lw = int(VIZ_CFG.get("trajectory_line_width", 4))
        for i, points in enumerate(particles):
            if len(points) < 2:
                continue
            poly = pv.PolyData(points)
            cells = np.full((1, len(points) + 1), len(points), dtype=np.int_)
            cells[0, 1:] = np.arange(len(points))
            poly.lines = cells
            plotter.add_mesh(poly,
                             color=colors[i % len(colors)],
                             line_width=lw,
                             label=labels[i] if i < len(labels) else f"Particle {i+1}")
        npts = sum(len(p) for p in particles)
        print(f"  Trajectories added in {time.time() - t0:.2f}s ({npts:,} points)")
    else:
        print("  WARNING: No trajectories found.")

    # 7. Оси, легенда, камера --------------------------------------------------
    plotter.show_bounds(
        grid="back", location="outer", all_edges=False,
        xtitle="X (meters)", ytitle="Y (meters)", ztitle="Z (meters)",
        font_size=10, color="black",
    )
    plotter.add_axes()
    try:
        plotter.add_legend(bcolor=None)
    except Exception:
        pass

    # Камера из visualizer.json (раздел camera).
    cam = VIZ_CFG.get("camera", {})
    plotter.camera_position = [
        tuple(cam.get("position", [7.0, 0.5, 15.0])),
        tuple(cam.get("focus",    [7.0, 0.5,  0.0])),
        tuple(cam.get("up",       [0.0, 1.0,  0.0])),
    ]
    # Параллельная (ортографическая) проекция -- параллельные линии
    # остаются параллельными, без перспективного схождения.
    # Управляется "parallel_projection" в visualizer.json (default true).
    if cam.get("parallel_projection", True):
        plotter.enable_parallel_projection()

    print(f"\nTotal scene preparation: {time.time() - t_start:.2f}s")
    print("--- Opening 3D window ---")
    plotter.show()


if __name__ == "__main__":
    exp_id = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    visualize(exp_id)
